### ISSUE TITLE
Check 301

### ISSUE THREAD

**Issue by Michaelh818** [Michaelh818/ADA-Compliance#3]
1.4 Distinguishable: Make it easier for users to see and hear content including separating foreground from background.
Success Criteria 1.4.3 Contrast (Minimum) (AA)
Check 301: The contrast between the colour of text and its background for the element is not sufficient to meet WCAG2.0 Level AA.

Repair: Use a colour contrast evaluator to determine if text and background colours provide a contrast ratio of 4.5:1 for standard text, or 3:1 for larger text. Change colour codes to produce sufficient contrast. http://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html#visual-audio-contrast-contrast-resources-head

PLUGIN: GRAVITY FORMS
<label class='gfield_label gfield_label_before_complex'  >Name<span class='gfield_required'>*</span> ...

The label is hidden what is the issue?  Does adding this css fix it?  IT should but this is dumb because it needed inline styles....

How i did it was I put the gform css in the header of theme file.

Then I took the javascript for it and put it underneathe the form html after grabbing from the builder version.

```css
/* ADA COMPLIANT CSS */
/* requires labels and colors for them to pass contrast even though they were hidden */

.gform_wrapper form li, .gform_wrapper li {
    color: #fff!important;
}

.gform_wrapper .screen-reader-text, .gform_wrapper label.hidden_sub_label {
    color: #fff !important;
}

.gform_wrapper .gfield_required {
    color: #ffffff !important;
}
```
